services:
  image-service:
    container_name: image-service
    build: .
    image: image-service
    ports:
      - 3000:3000
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/Development/cnd/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" /data
