services:
  image-service:
    container_name: image-servie
    build: .
    image: image-service
    ports:
      - 3000:3000
    networks:
      - rede-rede-network
      - image-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    networks:
      image-network:
        ipv4_address: 172.16.238.10
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: sh
    command: -c 'mc mb data/image-bucket && usr/bin/minio server --console-address ":9090" --address ":9000" /data'

volumes:
  minio_data:
