services:
  imageservice:
    container_name: imageservice
    build: .
    image: imageservice
    ports:
      - 3000:3000
    networks:
      - rede-rede-network
      - image-network

  minio:
    image: minio
    build: ./minio/.
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    networks:
      - image-network
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
  minio_data:
