version: "3.9"

include:
  - ./image-service/docker-compose.yaml
  - ./booking-service/docker-compose.yaml
  - ./user-service/docker-compose.yml
  - ./analytics-service/docker-compose.yml

services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - 8084:8084
    networks:
      - rede-rede-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - imageservice
      - bookingservice
      - userservice
      - analyticsservice
    networks:
      - rede-rede-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - rede-rede-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - rede-rede-network

networks:
  rede-rede-network:
    driver: bridge
  image-network:
    driver: bridge
