apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          imagePullPolicy: IfNotPresent
          image: ghcr.io/jannikfg/cloudnativedevelopment2023/minio:latest
          envFrom:
            - configMapRef:
                name: minio-config
          volumeMounts:
            - mountPath: /data
              name: minio-volume
          ports:
            - containerPort: 9000
              name: app
            - containerPort: 9090
              name: console
      imagePullSecrets:
        - name: ghcr-login-secret
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      name: app
      targetPort: app
    - port: 9090
      name: console
      targetPort: console
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
  labels:
    app: minio
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
