apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-analyticsservice
spec:
  selector:
    matchLabels:
      app: postgres-analyticsservice
  template:
    metadata:
      labels:
        app: postgres-analyticsservice
    spec:
      containers:
        - name: postgres-analyticsservice
          imagePullPolicy: IfNotPresent
          image: postgres:15.1-alpine
          envFrom:
            - configMapRef:
                name: postgres-analyticsservice-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-analyticsservice-volume
          ports:
            - containerPort: 5432
              name: app
      volumes:
        - name: postgres-analyticsservice-volume
          persistentVolumeClaim:
            claimName: postgres-analyticsservice-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-analyticsservice
spec:
  selector:
    app: postgres-analyticsservice
  ports:
    - port: 5432
      targetPort: app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-analyticsservice-config
data:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: analyticsservice
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-analyticsservice-pv-claim
  labels:
    app: postgres-analyticsservice
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
