version: "3.9"

services:
  postgres-userservice:
    image: postgres:15.0
    container_name: postgres-userservice
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userservice
    networks:
      - rede-rede-network
  userservice:
    image: userservice
    container_name: userservice
    build:
      context: .
    ports:
      - 8081:8081
    depends_on:
      - postgres-userservice
    networks:
      - rede-rede-network
