services:
  postgres-bookingservice:
    image: postgres:15.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookingservice
